---
# tasks file for ansible-role

- name: Check system
  assert:
    that: ansible_distribution == 'Debian'
      or ansible_distribution == 'Ubuntu'

- name: "Add the packages.microsoft apt key"
  get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: /etc/apt/trusted.gpg.d/
    mode: 0644
    owner: root
    group: root
  register: vscode_import_key
  retries: 3
  delay: 3
  until: vscode_import_key is succeeded

- name: "Add VSCode repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] \
            https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
  register: vscode_add_repository
  when: vscode_import_key is succeeded

- name: "Install VSCode stable"
  ansible.builtin.package:
    name: code
    state: present
  register: vscode_stable_installed
  when: vscode.install.stable
    and vscode_add_repository is succeeded
  retries: 3
  delay: 3
  until: vscode_stable_installed is succeeded

- name: "Install VSCode insiders"
  ansible.builtin.package:
    name: code-insiders
    state: present
  register: vscode_insiders_installed
  when: vscode.install.insiders
    and vscode_add_repository is succeeded
  retries: 3
  delay: 3
  until: vscode_insiders_installed is succeeded
