---
# tasks file for ansible-role

- name: Check system
  assert:
    that: ansible_distribution == 'Debian'
      or ansible_distribution == 'Ubuntu'

- name: "Add the HashiCorp apt key"
  get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: 0644
    owner: root
    group: root
  register: hashicorp_import_key
  retries: 3
  delay: 3
  until: hashicorp_import_key is succeeded

- name: "Add HashiCorp repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com \
            {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
  register: hashicorp_add_repository
  when: hashicorp_import_key is succeeded

- name: "Install HashiCorp Packer"
  ansible.builtin.package:
    name: packer
    state: present
  register: hashicorp_packer_installed
  when: hashicorp.install.packer
    and hashicorp_add_repository is succeeded
  retries: 3
  delay: 3
  until: hashicorp_packer_installed is succeeded

- name: "Install HashiCorp Vagrant"
  ansible.builtin.package:
    name: vagrant
    state: present
  register: hashicorp_vagrant_installed
  when: hashicorp.install.vagrant
    and hashicorp_add_repository is succeeded
  retries: 3
  delay: 3
  until: hashicorp_vagrant_installed is succeeded

- name: "Install HashiCorp Terraform"
  ansible.builtin.package:
    name: terraform
    state: present
  register: hashicorp_terraform_installed
  when: hashicorp.install.terraform
    and hashicorp_add_repository is succeeded
  retries: 3
  delay: 3
  until: hashicorp_terraform_installed is succeeded
