---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Verify apt key
      ansible.builtin.stat:
        path: /etc/apt/trusted.gpg.d/docker.asc
        checksum_algorithm: sha256
      register: apt_key
      failed_when: "apt_key.stat.checksum != \
        '1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570'"
    - name: Verify apt repository
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/docker.list
        checksum_algorithm: sha256
      register: apt_repository
      failed_when: "apt_repository.stat.checksum != \
        '958ae316a7047dc8c484175e83f244a3ec5c1c740337b1b19b3313821ecf72af'"
    - name: Verify docker-ce package
      ansible.builtin.package:
        name: docker-ce
        state: present
      check_mode: true
    - name: Verify docker-ce-cli package
      ansible.builtin.package:
        name: docker-ce-cli
        state: present
      check_mode: true
    - name: Verify containerd.io package
      ansible.builtin.package:
        name: containerd.io
        state: present
      check_mode: true
