---
# tasks file for ansible-role

- name: Check system
  assert:
    that: ansible_distribution == 'Debian'
      or ansible_distribution == 'Ubuntu'

- name: "Add the docker key"
  get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644
    owner: root
    group: root
  register: docker_import_key
  retries: 3
  delay: 3
  until: docker_import_key is succeeded
  become: yes

- name: "Add docker repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] \
           https://download.docker.com/linux/{{ ansible_distribution | lower }} \
           {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  register: docker_add_repository
  when: docker_import_key is succeeded
  retries: 3
  delay: 3
  until: docker_add_repository is succeeded
  become: yes

- name: "Install [docker-ce]"
  ansible.builtin.package:
    name: docker-ce
    state: present
  register: docker_installed
  when: docker_add_repository is succeeded
  retries: 3
  delay: 3
  until: docker_installed is succeeded
  become: yes

- name: "Install [docker-ce-cli]"
  ansible.builtin.package:
    name: docker-ce-cli
    state: present
  register: docker_ce_cli_installed
  when: docker_add_repository is succeeded
  retries: 3
  delay: 3
  until: docker_ce_cli_installed is succeeded
  become: yes

- name: "Install [containerd.io]"
  ansible.builtin.package:
    name: containerd.io
    state: present
  register: containerd_installed
  when: docker_add_repository is succeeded
  retries: 3
  delay: 3
  until: containerd_installed is succeeded
  become: yes

- name: "Use Buildx"
  ansible.builtin.command: docker buildx install
  when: docker_ce_cli_installed is succeeded
    and docker.use_buildx
  changed_when: false

- include_tasks: docker-compose.yml
  when: docker.install_compose | bool
