---
name: roles test

on:
  push:
    branches: [ main, develop ]
    paths:
      - ".github/workflows/roles.yml"
      - "roles/*/**"

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role: [ debase, conda, docker, hashicorp,
                nodejs, rust, realvnc, vscode ]
    defaults:
      run:
        working-directory: roles/${{ matrix.role }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: printf '[defaults]\nroles_path=../' >ansible.cfg
      - run: ansible-playbook tests/test.yml -i tests/inventory.yml --syntax-check

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role: [ debase, conda, docker, hashicorp,
                nodejs, rust, realvnc, vscode ]
    defaults:
      run:
        working-directory: roles/${{ matrix.role }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r dev-requirements.txt
      - name: Molecule
        #        env:
        #          MOLECULE_PLAYBOOK: converge-github.yml
        run: molecule test
